### ISSUE TITLE
Resizing logo probleem

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#1]
Bij het configureren van de LegitiMaat obv template krijg ik de resizing van het logo niet op orde. 

Met deze config krijg het resultaat zoals in screenshot bijgevoegd. Enig idee hoe dit te fixen?
```
  nl_logo: {
    src: "https://open-regels.nl/assets/images/legitimaat-logo.svg",
    alt: "LegitiMaat-logo",
    id: "MinBZK",
    height: 600,
    width: 600,
    url: "https://open-regels.nl",
  },
```

![image](https://user-images.githubusercontent.com/25812095/175881269-e1e30326-91d6-46cc-bd32-96787c7ac7b3.png)

**Comment by sgort** [comment]
De versie met height en width beiden 300 ziet er zo uit.

![image](https://user-images.githubusercontent.com/25812095/175882106-63e297f5-4c9a-4c39-9793-d5a64f225f43.png)

**Comment by sanderke** [comment]
De SVG zelf bevat aardig wat white space om het logo heen:
![knip](https://user-images.githubusercontent.com/25407617/175893642-4965aef9-596f-4f69-a5e8-17e67bc8ded8.png)

**Comment by sgort** [comment]
Ah check. Dat kan anders idd. Fixen we dat eerst.

**Comment by sgort** [comment]
Tijdelijk zelf even opgelost met een png variant die ik nog ergens had. De aangepaste svg volgt later. Na de toetsweek van de designer. ;-)
