### ISSUE TITLE
Logius vs BZK

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#10]
Ik neem aan dat om van Logius -> BZK te maken in de blauwe gekantelde balk linksboven een apart BZK profiel moet worden gemaakt? Of valt dat nog ergens te configureren?
![image](https://user-images.githubusercontent.com/25812095/176677961-86088715-d2e7-4642-a59c-48cd89b1ff47.png)

PS
Over dat BZK profiel ja/nee kom ik overigens ná de publicatie van De LegitiMaat (morgen!) bij je op de lijn.

**Comment by sanderke** [comment]
Tijdelijke "oplossing":
```diff
-nl_organisationPrefix: "LS-",
+nl_organisationPrefix: "GN-",
```
De combinatie `GN-` (Geonovum) en `specStatus: "DEF"` verwijst naar een niet-bestaande locatie voor de zijbalk-SVG.

Het versienummer kan uit de titel gelaten worden met `nl_addReleaseTagTitle: false,`, indien gewenst.
