### ISSUE TITLE
Respec-template voor BZK

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#11]
Voor de publicatie van De LegitiMaat is gebruik gemaakt van het Logius Respec-template. De idee is om nu een BZK specifieke variant te maken.

Zonder compleet te zijn:
- [ ] organisatie-specifiek profiel voor BZK en/of NL?
- [ ] gebruik [NL Design System](https://www.nldesignsystem.nl/docs/meedoen/introductie) voor huisstijl indien van toepassing
- [ ] automatiseren Markdown <> Word conversie in het publicatieproces (ie [pandoc](https://pandoc.org/index.html) wellicht bruikbaar?)
- [ ] scenario('s) voor koppeling publicatieserver
- [ ] wat ik nog vergeten ben...

Laat me even weten wat de beste manier is om dit op te pakken. Een fork van deze repo bij [BZK](https://github.com/MinBZK/) en daar een branch voor het nieuwe profiel? Of anders?

**Comment by nicorikken** [comment]
Pandoc is inderdaad in staat om .odt en .docx bestanden te generen. Ik herinner me uit mijn experimenten uit het verleden dat het dan handig is om een template bestand aan te bieden om een leesbare stijl over te houden.

Verder zou ik bestanden toevoegen die naar de buitenwereld communiceren over de publieke repository:

- README.md dat het project en proces samenvat, uitgaande van gangbare conventies
- CODE_OF_CONDUCT.md met gedragsregels
- CONTRIBUTING.md met beschrijving hoe bij te dragen
- LICENSE bestand dat de licentietekst bevat
- PROJECT_GOVERNANCE.md over de beheerstructuur van het project
- SUPPORT.md met beschrijving hoe in contact te komen voor ondersteuning (meer iets voor software)
- ISSUE_TEMPLATE en PULL_REQUEST_TEMPLATE in een .github map om een standaard format te hebben bij nieuwe issues/pull-requests

Zie hier een voorbeeld van die documenten in de praktijk van een repository van mijn werkgever: https://github.com/alliander-opensource/power-grid-model

**Comment by sanderke** [comment]
> organisatie-specifiek profiel voor BZK en/of NL?

Deze repository bevat een basis ReSpec-document. De organisatiespecifieke zaken komen vanuit de ReSpec build met Logius-profiel dat vanuit index.html wordt aangeroepen:
https://github.com/Logius-standaarden/ReSpec-template/blob/7077b4f7d93ef942cb92daad089fd0510f4df125/index.html#L10
In de [ReSpec repository](https://github.com/Logius-standaarden/respec) (fork van W3C) wordt aan het Logius-profiel gewerkt. Een BZK-variant zou in dezelfde repository kunnen leven zoals [de bestaande profielen](https://github.com/Logius-standaarden/respec/tree/develop/profiles), dus branches of forks zijn niet noodzakelijk. Mogelijk wordt samen met Geonovum een nieuwe GitHub-organisatie opgesteld om de repository te huisvesten voor samenwerking. Als men in de tussentijd wil sleutelen aan een BZK-variant zou een fork van de Logius ReSpec repo aangeraden zijn.

> scenario('s) voor koppeling publicatieserver

Door middel van [GitHub Actions](https://github.com/Logius-standaarden/Digikoppeling-Koppelvlakstandaard-REST-API/actions/runs/2880826188) genereren wij een statische HTML pagina en PDF voor publicatie en het uitvoeren van controles (kleurcontrast e.d. voor WCAG en gebroken links). Vervolgstappen zullen afhankelijk zijn van de publicatieomgeving; ons script kopieert bijvoorbeeld de statische bestanden naar een [publicatierepo](https://github.com/Logius-standaarden/publicatie) dat dagelijks naar logius.nl getrokken wordt.

**Comment by nicorikken** [comment]
Als het vanuit één template kan werken is dat zeker makkelijker.

<hr>

> Verhuis binnenkort met regels.overheid.nl van gitlab naar github MinBZK.

@sgort Beetje offoptic, maar GitLab is tenminste nog (grotendeels) open source en GitHub totaal niet. Ik snap wel de wens om naar één platform te bewegen om het overzichtelijk te houden, maar dit lijkt mij een beweging de verkeerde kant op, ook volgens inkoopregels (open, tenzij). [Common Ground is ook juist gevestigd op GitLab](https://gitlab.com/commonground). Ik hoop dat er voor de overheid in de toekomst zelfs een eigen code-infastructuur komt (al dan niet uitbesteed) die beter aansluit bij publieke waarden.

**Comment by sgort** [comment]
I know @nicorikken , punt is dat MinBZK géén presence heeft op GitLab en wel op github. Ik sluit zelf niet per se uit dat we tzt een gitlab omgeving optuigen voor MinBZK en github verlaten. Maar daar ga ik uiteindelijk niet over. Ma spreek ik Koos Steenbergen weer. Die gaat over open source binnen BZK.

**Comment by sgort** [comment]
Van deze originele issue zijn aparte issues aangemaakt op https://github.com/Logius-standaarden/respec/issues
Deze issue kan worden gesloten.
