### ISSUE TITLE
ReSpec sync procedure

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#15]
- voor de ontwikkeling van het "NL-profiel" én in sync houden met W3C is er [respec](https://github.com/Logius-standaarden/respec)
- voor het toepassen van ReSpec is er deze [respec-template](https://github.com/Logius-standaarden/respec-template)

Nu vraag ik mij het volgende af: na toepassen respec-template, zoals bijv. voor [De LegitiMaat](https://github.com/MinBZK/LegitiMaat), wat moet ik doen (of laten) om daar óók in sync te blijven met de ontwikkeling van het "NL-profiel"?

PS
Wellicht idee om dat nog kort toe te lichten in de README van deze template?

**Comment by sanderke** [comment]
Door te verwijzen naar een centraal gehoste build zal altijd de meest recente versie ingeladen worden. In het geval van breaking changes zullen deze als error zichtbaar worden in een dynamisch document indien relevant. Door enkel statische snapshots te publiceren zullen bestaande publicaties niet onverwachts wijzigen.

De huidige `logius-respec.js` (op _centrumvoorstandaarden.nl_) zal voorlopig bereikbaar blijven. De eerste build van het "NL-profiel" zal elders gehost worden (waarschijnlijk _logius.nl_). Het adres zal in de template gewijzigd worden en in dit issue gemeld worden.

**Comment by sanderke** [comment]
De naam en locatie van het profiel is bekend:
`https://gitdocumentatie.logius.nl/publicatie/respec/builds/respec-nlgov.js`

Template is aangepast met nieuwe configuratiebestanden vanwege de overstap naar een generiek profiel. Nieuwe versies van het profiel zullen op het bovenstaande adres beschikbaar komen.
