### ISSUE TITLE
Begrippenlijst opnemen als Terms defined by - hoe te doen?

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#2]
Ik heb een apart md bestand voor **2. Begrippenlijst**: https://sgort.github.io/LegitiMaat/#begrippenlijst

Zie die graag in de **A. Index** maar kan niet ontdekken hoe dat te doen.

![image](https://user-images.githubusercontent.com/25812095/175936305-e6b07b46-68e5-458b-b012-7b0f5460d014.png)

**Comment by sgort** [comment]
Het valt me overigens nu pas op dat de template voor Index Engelse teksten gebruikt. De rest is wel Nederlands. Hoe dat aan te passen?

![image](https://user-images.githubusercontent.com/25812095/175956456-03c33d13-8a5f-4418-a13c-64b71ce5d10c.png)

**Comment by sanderke** [comment]
Er is nog geen Nederlandse vertaling in [dfn-index](https://github.com/Logius-standaarden/respec/blob/02f753dc34e8a6258b5591e6ac7f5f11c44c3482/src/core/dfn-index.js#L18).

**Comment by sgort** [comment]
Dank. En ik realiseerde me net dat ik niet eerste naar de Respec-test had gekeken voor dat ik de issue aanmaakte. Dom van me.

**Comment by sgort** [comment]
> Er is nog geen Nederlandse vertaling in [dfn-index](https://github.com/Logius-standaarden/respec/blob/02f753dc34e8a6258b5591e6ac7f5f11c44c3482/src/core/dfn-index.js#L18).

[PR](https://github.com/Logius-standaarden/respec/pull/12) gedaan

**Comment by sanderke** [comment]
PR doorgevoerd. Bedankt

Een nieuwe build staat live. Als het effect niet zichtbaar is zal het legen van browser cache helpen (of de pagina in _InCognito_-mode o.i.d. bekijken). De ReSpec-knop rechtsboven zou versie `32.1.10 Logius profile 20220628` moeten tonen.
