### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by PHaasnoot** [Logius-standaarden/ReSpec-template#20]
Als je geen parameter NL-logo aangeeft is nu het default logo Geonovum,
het is wenselijk om ook aan te kunnen geven dat je geen logo gebruikt, naast een eigen organisatie default voor het generieke profiel

**Comment by CHAOSdonut** [comment]
dit is opgelost in https://github.com/Logius-standaarden/respec/pull/17/commits/dddf5e482bf6a413a555af4ff31d4630cc9aa283
