### ISSUE TITLE
Check links failed - no clue hoe en waarom

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#23]
Bij toepassing respec-template voor [De LegitiMaat](https://github.com/MinBZK/LegitiMaat) faalt de check links op `http://localhost:8080/marlies@hooghiemstra-en-partners.nl`

Geen idee hoe dat komt.

![image](https://user-images.githubusercontent.com/25812095/195840235-e3517900-c1b1-4262-8bc3-7762d25235d8.png)

**Comment by sanderke** [comment]
Op [regel 18 van De-LegitiMaat.EN.md](https://github.com/MinBZK/LegitiMaat/blob/245a1998f825717f56caf666f1f2bab042bddf01/De-LegitiMaat.EN.md?plain=1#L18) staat
`[Marlies van Eck](marlies@hooghiemstra-en-partners.nl)`
dit zou als volgt moeten zijn:
`[Marlies van Eck](mailto:marlies@hooghiemstra-en-partners.nl)`

**Comment by sgort** [comment]
Oeps. Dank voor je hulp. Die zag ik niet aankomen ;-)
