### ISSUE TITLE
Standaard teksten die horen bij specStatus

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#3]
De `specStatus: "WV"` levert deze tekst op. Waar is dat te configureren?

![image](https://user-images.githubusercontent.com/25812095/175954408-008befaf-84f6-43d4-979c-70fc34bb4d79.png)

**Comment by sanderke** [comment]
Deze tekst komt uit het Logiusprofiel en kent deze opmaak:
`Dit is een werkversie die op elk moment kan worden gewijzigd, verwijderd of vervangen door andere documenten. Het is geen door ${opts.operationalCommittee} goedgekeurde consultatieversie.`

De waarde van `operationalCommittee` volgt [hier](https://github.com/Logius-standaarden/respec/blob/02f753dc34e8a6258b5591e6ac7f5f11c44c3482/src/logius/headers.js#L703) uit:
```js
get operationalCommittee() {
      let operationalCommittee = "";

      switch (conf.nl_organisationName.toLowerCase()) {
        case "logius":
          operationalCommittee = "het Technisch Overleg";
          break;
        default:
          // Geonovum = 1
          operationalCommittee = "de werkgroep";
          break;
      }
```

Hier lopen we dus tegen organisatiespecifieke termen aan in ReSpec. Een gezamenlijk profiel zou een groeiende lijst hebben tenzij de `operationalCommittee` variabele naar `config.js` van het document wordt verhuisd.

Als de zin zelf niet volstaat zal dit in [sotd.js](https://github.com/Logius-standaarden/respec/blob/develop/src/logius/templates/sotd.js) in het ReSpec-profiel aangepast moeten worden.

**Comment by sgort** [comment]
Helder. Stel voor dit ná eerste publicatie LegitiMaat af te stemmen. Hoe en wat omtrent BZK profiel...

**Comment by mvb-nerdzone** [comment]
Wellicht interessant om te weten: Ik heb een wat algemenere oplossing bedacht, waarbij e.e.a. configureerbaar is in de `config.js`. Zie Logius-standaarden/ep-algemeen#4.

@sanderke - wellicht interessant om het ook op een dergelijke manier in het template te zetten, of is deze oplossing niet helemaal de juiste manier?

**Comment by sanderke** [comment]
Zoals @mvb-nerdzone al naar verwijst is het tegenwoordig wel configureerbaar met `sotdText`:
https://github.com/Logius-standaarden/ReSpec-template/blob/f637ee2dd6534b926b92ab5b627a994db8cf7974/js/organisation-config.js#L65-L73
