### ISSUE TITLE
Geen config.js voor title in index.html

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#33]
De `<title>Default</title>` in `index.html` kent nog geen relatie met de `title: "DCAT-AP-RONL (concept)",` die ik in `config.js` hanteer voor [mijn profiel](https://minbzk.github.io/dcat-ap-ronl/).

Nu moet ik dus nog de html editen. Niet?

**Comment by sanderke** [comment]
Als het goed is komt de relatie uit de regel erboven en is `Default` enkel een place-holder:

```html
<script>document.title = respecConfig.title</script>
<title>Default</title>
```

**Comment by sanderke** [comment]
De preview kijkt waarschijnlijk niet verder dan `<title>`. Dat is misschien wel een puntje. De statische pagina ("snapshot" voor publicatie) heeft dit probleem gelukkig niet.
