### ISSUE TITLE
statische doc.pdf wordt niet aangemaakt.

### ISSUE THREAD

**Issue by wilkoquak** [Logius-standaarden/ReSpec-template#34]
Volgens de readme wordt er automatisch een snapshot.html en een doc.pdf aangemaakt. In de template zie ik wel de snapshot.html, maar de doc.pdf zie ik niet.

**Comment by sanderke** [comment]
Bedankt. Het aanmaken van de PDF stond uitgecommentarieerd. Dit is aangepast (en hernoemd in de readme), zie [template.pdf](https://github.com/Logius-standaarden/ReSpec-template/blob/main/template.pdf).
