### ISSUE TITLE
Create Issue - Issue

### ISSUE THREAD

**Issue by mvb-nerdzone** [Logius-standaarden/ReSpec-template#37]
Als ik een nieuw issue wil maken, krijg ik de keuze om Digikoppeling-aanpassingen te doen. Kan dat aangepast worden, zodat het duidelijk is dat dit gaat over de Respec-template?

![20230130 0017 respec-template-create-issue-issue](https://user-images.githubusercontent.com/63168360/215513842-d02b16ee-19d0-4399-a044-6890468039de.png)

**Comment by sanderke** [comment]
We gaan over naar een meer specifiek template voor eigen gebruik.
