### ISSUE TITLE
Licentie-svg's in organisation.config.js verwijzen naar tools.geostandaarden.nl

### ISSUE THREAD

**Issue by mvb-nerdzone** [Logius-standaarden/ReSpec-template#38]
In [organisation.config.js](../blob/main/js/organisation-config.js) wordt nog verwezen naar geostandaarden.nl. bijvoorbeeld:

`image: "https://tools.geostandaarden.nl/respec/style/logos/cc-by-nd.svg"`

Is dat bewust? Zou het niet beter zijn om dit ook op de centrale plek `"https://gitdocumentatie.logius.nl/publicatie/"` te hosten of desnoods te verwijzen naar de betreffende badges hier: https://creativecommons.org/about/downloads/ ?

**Comment by sanderke** [comment]
Bedankt!
