### ISSUE TITLE
Begrippenlijst rendering vertoont kuren

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#4]
De lijst begrippen onder **A.1 Begrippen gedefinieerd door deze specificatie** vertoont kuren die lastig uit te leggen zijn. Heb een screenrecording uploaded naar YT (github support dit niet) die laat zien wat ik bedoel: https://youtu.be/tUN0bibtqFo

Je kan ook naar de [live pagina](https://sgort.github.io/LegitiMaat/#index-defined-here) gaan en na de eerste poging opnieuw op het begrip Voorbereidingshandelingen klikken.

**Comment by sanderke** [comment]
Dat ziet er komisch frustrerend uit. De inhoud van [`base.css`](https://publicatie.centrumvoorstandaarden.nl/respec/style/base.css) was even overschreven met de inhoud van de huidige W3C versie. Dit leek het probleem op te lossen. De oude versie is wel weer teruggezet vanwege de WCAG-gerelateerde wijzigingen.
