### ISSUE TITLE
Voorbeeld links uit te sluiten bij check?

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#40]
Deze publicatie (WIP) heeft voorbeeld url's die niet resolven: https://minbzk.github.io/Algoritmeregister-Publicatiestandaard/#link-naar-publiekspagina

Consequentie is dat de `Build and Check` action failed.

Zijn dit soort voorbeeld url's uit te sluiten?

**Comment by sanderke** [comment]
Wij zetten voorbeeld-URL's tussen backticks (`https://algoritmes.gemeentenoorderhaaks.nl/`) i.p.v. een klikbare dode link (https://algoritmes.gemeentenoorderhaaks.nl/).
