### ISSUE TITLE
Hoe xref te configureren?

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#5]
Ik was in de veronderstelling dat ik met enabling automatic external reference linking via [config.js](https://github.com/sgort/LegitiMaat/blob/20e45bfbe0f0c0e0a73813ab1d3400e563422c8d/js/config.js#L89) icm de juiste shorthands deze vanzelf onder het kopje **Begrippen gedefinieerd door verwijzing** zou aantreffen. Dat is ten dele waar.

Voor [event handler](https://respec.org/xref/?term=event+handler) gaat dat goed.

![image](https://user-images.githubusercontent.com/25812095/176163616-f28ce4c2-9deb-4a23-8e55-486e962a46ce.png)

Voor [url parser](https://respec.org/xref/?term=url+parser) gaat dat fout.

![image](https://user-images.githubusercontent.com/25812095/176163537-3ac9cda6-f05f-4885-a372-5b9ea6cacb97.png)

Is de reden dat ik wél **[HTML]** als cited document heb en niet **[URL]**?!

**Comment by sgort** [comment]
Met **[URL]** toegevoegd
![image](https://user-images.githubusercontent.com/25812095/176167481-456b7db2-9236-4c88-b8a2-18d3ea04bf15.png)
krijg ik
![image](https://user-images.githubusercontent.com/25812095/176167555-c6d438f7-1796-4ede-91f3-a11dfb2576a2.png)

**Comment by sanderke** [comment]
De scope is kennelijk beperkt tot "this document or other cited documents", maar gelukkig hoeven "cited documents" niet in de proza genoemd te worden; `URL` kan ook in config.js genoemd worden:
```diff
- xref: true,
+ xref: ["URL"],
```
