### ISSUE TITLE
Hoe werkt linken in ReSpec document zelf?

### ISSUE THREAD

**Issue by sgort** [Logius-standaarden/ReSpec-template#8]
Ik wil in de tekst van hoofdstuk 1 het woord *visitatie-instrument* linken naar hoofdstuk 2.

Als ik dat op deze wijze `Het is een [visitatie-instrument](https://minbzk.github.io/LegitiMaat/#de-legitimaat-als-visitatie-instrument).` doe dan werkt het op de dynamische pagina,

![image](https://user-images.githubusercontent.com/25812095/176618272-0a4ace57-7d0d-4080-aaf4-63a0fb0cbaf4.png)

maar (terecht) **NIET** in de snapshot..

Overigens, in de build zie ik deze fout voorbij komen
![image](https://user-images.githubusercontent.com/25812095/176618513-4c4f9de4-6eda-46f1-a592-494fa16210ec.png)

Kortom, de vraag is: hoe doe ik linken in het ReSpec document zelf correct?

**Comment by sanderke** [comment]
Linken binnen een pagina kan door enkel naar de anchor te verwijzen:
`Het is een [visitatie-instrument](#de-legitimaat-als-visitatie-instrument).`

Dit is niet specifiek voor ReSpec. ReSpec zelf biedt ook de mogelijkheid om de naam een nummer van een sectie te tonen. In het voorbeeld wordt `[[[#tof]]]` weergegeven als _4. Lijst met figuren_.
